//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::tag::Entity as Tag;
pub use super::url::ActiveModel as UrlActiveModel;
pub use super::url::Entity as Url;
